import { NextResponse } from "next/server";
import { currentUser } from "@/lib/server/auth";
import { getEncounter, recordAuditServer } from "@/lib/server/db";
import { dictateSchema, safeParse } from "@/lib/validation";
import { csrfGuard } from "@/lib/server/csrf";
import { rateLimit, routeRateLimitKey } from "@/lib/server/rateLimit";
import { parseDictatedRx, type RxItem } from "@/lib/clinical";
import { llmJson } from "@/lib/server/llm";
import { canUseExternalModel } from "@/lib/consent";
import { bodyTooLarge, payloadTooLarge } from "@/lib/server/bodyLimit";
import { log } from "@/lib/server/log";

export const runtime = "nodejs";

type LlmRx = { items?: Array<{ name?: string; dosage?: string; frequency?: string; duration?: string; instructions?: string }> };

/**
 * AI scribe: turn a doctor's free-text dictation into a structured prescription
 * draft. Uses the LLM when OPENAI_API_KEY is set, otherwise a deterministic
 * rule-based parser — both offline-safe and verifiable.
 */
export async function POST(req: Request) {
  if (!rateLimit(routeRateLimitKey(req), 30, 60_000)) {
    return NextResponse.json({ ok: false, error: "Rate limit" }, { status: 429 });
  }
  const csrf = csrfGuard(req);
  if (!csrf.ok) return NextResponse.json({ ok: false, error: csrf.error }, { status: 403 });

  const user = await currentUser();
  if (!user) return NextResponse.json({ ok: false, error: "Authentication required." }, { status: 401 });
  if (bodyTooLarge(req, 64 * 1024)) return payloadTooLarge();

  const body = await req.json().catch(() => ({}));
  const parsed = safeParse(dictateSchema, body);
  if (!parsed.ok) return NextResponse.json({ ok: false, error: parsed.error }, { status: 400 });

  const { text, encounterId } = parsed.data;
  let draft: RxItem[] = [];
  let hinted = false;

  // The dictation routinely contains patient details the doctor speaks aloud.
  // When it is linked to a stored encounter, that record's `ai_processing`
  // scope decides whether an external model may see the text — same rule as
  // /api/summarize and /api/patient/[id]/ai. Unlinked dictation (no stored
  // consent to consult) keeps the previous behaviour.
  let allowExternalModel = true;
  let linked: Awaited<ReturnType<typeof getEncounter>> = null;
  if (encounterId) {
    linked = await getEncounter(encounterId);
    allowExternalModel = !!linked && canUseExternalModel(linked.consent);
  }

  const llm = allowExternalModel
    ? await llmJson<LlmRx>(
        "You are a hospital pharmacist's assistant. Convert the doctor's dictation into a structured prescription. " +
          "Return strictly JSON: {\"items\":[{\"name\":\"generic drug name\",\"dosage\":\"e.g. 500mg\",\"frequency\":\"e.g. thrice daily\",\"duration\":\"e.g. 5 days\",\"instructions\":\"short note\"}]}. " +
          "Only include medications explicitly mentioned. Never invent doses.",
        { text }
      )
    : null;
  if (llm?.items?.length) {
    hinted = true;
    draft = llm.items
      .filter((i) => i.name)
      .map((i) => ({ name: i.name as string, dosage: i.dosage, frequency: i.frequency, duration: i.duration, instructions: i.instructions }));
  } else {
    draft = parseDictatedRx(text);
  }

  if (encounterId && linked) {
    await recordAuditServer(
      encounterId,
      "note_added",
      `AI scribe draft generated by ${user.username} (${hinted ? "LLM" : "rule-based"})`,
      user.username
    );
  }
  if (!draft.length) {
    return NextResponse.json({ ok: false, error: "No medication could be parsed from the dictation." }, { status: 422 });
  }
  log("info", "rx", "dictation parsed", { by: user.username, items: draft.length, hinted });
  return NextResponse.json({ ok: true, hinted, draft });
}