import type { StoredHistory } from "./types";

/** Stable demo encounter ids so repeated seeding never duplicates records. */
const DEMO_IDS = {
  sunita: "demo-sunita-devi",
  ramesh: "demo-ramesh-kumar",
  anita: "demo-anita-sharma",
};

function now(): string {
  return new Date().toISOString();
}

export function buildDemoPatients(): StoredHistory[] {
  const nowIso = now();
  const mk = (
    id: string,
    name: string,
    age: number,
    sex: "Male" | "Female",
    dept: string,
    complaint: string,
    hpi: string,
    opts: { urgent?: boolean; ayush?: boolean; meds?: string[]; abha?: string; vitals?: StoredHistory["patient"]["vitals"] } = {}
  ): StoredHistory => ({
    encounterId: id,
    updatedAt: nowIso,
    patient: {
      abhaId: opts.abha ?? "11-0000-0000-0002",
      name,
      age,
      sex,
      department: dept,
      mobile: "9876543210",
      vitals: opts.vitals,
    },
    mode: opts.ayush ? "ayush" : "allopathic",
    enteredAt: nowIso,
    history: {
      name,
      age,
      sex,
      chiefComplaint: complaint,
      hpi,
      pastMedical: [{ condition: "Hypertension" }],
      pastSurgical: [],
      medications: (opts.meds ?? ["Amlodipine 5mg"]).map((m) => ({
        name: m.replace(/ \d+.*$/, ""),
        dosage: m.match(/\d+\s?mg/)?.[0],
      })),
      allergies: [{ substance: "Penicillin" }],
      familyHistory: "Not elicited",
      personalHistory: "Smoking: no; Alcohol: no",
      reviewOfSystems: [{ system: "General", positive: "All systems negative" }],
      priorInvestigations: [],
      ayush: opts.ayush
        ? {
            prakriti: "Vata-Pitta",
            vikriti: "",
            sara: "",
            samhanana: "",
            pramana: "45 years",
            satmya: "",
            sattva: "Calm",
            aharaShakti: "",
            vyayamaShakti: "",
            vaya: "Madhyam",
            agni: "Irregular",
            koshtha: "Constipated",
            nidana: "",
            samprapti: "",
            aharaVihara: "Irregular meals",
          }
        : undefined,
    },
    documents: [],
    redFlags: opts.urgent
      ? [{ id: "rf-demo", severity: "high", symptom: complaint, message: "Demo priority alert — immediate review required.", source: "vitals" }]
      : [],
    interactions: [],
    summary:
      `${name}, ${age}y, ${sex} | ${opts.ayush ? "AYUSH (Ayurvedic)" : "Allopathic"}\n=============\nCHIEF COMPLAINT:\n• ${complaint}\n\nHISTORY OF PRESENT ILLNESS:\n • ${hpi}\n\nPAST MEDICAL HISTORY:\n • Hypertension\n\nCURRENT MEDICATIONS:\n • ${(opts.meds ?? ["Amlodipine 5mg"]).join(", ")}\n\nALLERGIES:\n • Penicillin\n\nGENERATED BY MEDIKIOSK (DEMO SEED)`,
    consentGranted: true,
    status: "pending",
    audit: [{ action: "consent_granted", at: nowIso }],
  });

  return [
    mk(
      DEMO_IDS.sunita,
      "Sunita Devi",
      62,
      "Female",
      "Cardiology",
      "Chest Pain",
      "Chest tightness on exertion since 3 days, radiates to left arm, relieved by rest.",
      {
        urgent: true,
        meds: ["Amlodipine 5mg", "Aspirin 75mg"],
        vitals: { systolic: 168, diastolic: 104, pulse: 98, weight: 64, height: 155, temperature: 37.1 },
      }
    ),
    mk(
      DEMO_IDS.ramesh,
      "Ramesh Kumar",
      58,
      "Male",
      "General Medicine",
      "Fever",
      "Low-grade fever with body ache for 4 days.",
      { meds: ["Paracetamol 650mg"], abha: "22-0000-0000-0017", vitals: { systolic: 128, diastolic: 82, pulse: 88, temperature: 38.6 } }
    ),
    mk(
      DEMO_IDS.anita,
      "Anita Sharma",
      45,
      "Female",
      "AYUSH - Ayurveda (General)",
      "Abdominal Pain",
      "Bloating and irregular digestion, constipation predominant.",
      { ayush: true, abha: "98-7654-3210-9873", vitals: { systolic: 118, diastolic: 76, pulse: 74, weight: 58, height: 160 } }
    ),
  ];
}

export { DEMO_IDS };